- hosts: all
  remote_user: ec2-user
  become: true
  tasks:

    - name: Install Apache middleware
      package:
        name: httpd
        state: present

    - name: Start Apache service
      service:
        name: httpd
        state: started

    - name: Copy index.html file to /var/www/html
      copy:
        src: index.html
        dest: /var/www/html

